### ISSUE TITLE
Impossible to Download the Dataset

### ISSUE THREAD

**Issue by omarmhaimdat** [Wangjing1551/LogoDet-3K-Dataset#7]
It is impossible to download the data since there is no way to create a Baidu account outside of China. Can you please make it accessible through any other worldwide available provider @Wangjing1551 ?

ps: If anyone managed to download the dataset please host it on an easily accessible platform, thank you!

**Comment by druefena** [comment]
I just found the dataset is also hosted on Kaggle, so people outside China should also be able to download it here:
https://www.kaggle.com/datasets/lyly99/logodet3k
